### ISSUE TITLE
feat: 팝업스토어의 방문자 수, 즐겨찾기 기능 추가 및 Redis 설정 및 Batch 모듈을 추가한다

### ISSUE THREAD

**Issue by sosow0212** [sosow0212/2024-pop-cloud#14]
### ✨ Describe

추후 인기 팝업스토어 조회를 위해 방문자 및 즐겨찾기 기능을 추가하고, 이를 관리하는 Redis 캐싱을 적용합니다.
**--> 인기 팝업스토어 캐싱 조회 기능은 구현 예정입니다. 현재 이슈에서 작업 범위가 너무 커서 다른 Issue를 열어 진행할 예정입니다.**  

## TODO
- [x] 도메인에 방문자 수 및 즐겨찾기를 관리하는 필드 및 도메인 메서드 추가
- [x] Redis 설정을 진행한다
- [x] batch 모듈을 생성한다.

## 다음 이슈에서 진행할 TODO
- [ ] 기능을 위해 인기 팝업스토어 캐싱하는 기능 추가
- [ ] batch 모듈에서 스케줄러를 통해 5분마다 Redis 조회수 및 좋아요를 수치화해서 특정 등수의 팝업스토어를 캐싱한다 (스케일아웃 상황에서 중복 스케줄링 해결하기)
